# Generated by Django 5.2.1 on 2025-06-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='user.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.language'),
        ),
        migrations.AddField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('Y', 'YORUBA'), ('H', 'HAUSA'), ('I', 'IGBO')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('A', 'AVAILABLE'), ('B', 'BORROWED'), ('C', 'MAINTENANCE')], default='A', max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('R', 'ROMANCE'), ('D', 'COMEDY'), ('P', 'POLITICS'), ('F', 'FINANCE')], default='F', max_length=1, unique=True),
        ),
    ]
