# Generated by Django 5.2.1 on 2025-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_book_author_book_language_language_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('Y', 'YORUBA'), ('H', 'HAUSA'), ('I', 'IGBO')], default='Y', max_length=2),
        ),
    ]
