# Generated by Django 5.2.1 on 2025-07-02 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_author_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dob',
            field=models.DateField(default=datetime.datetime(2025, 7, 2, 13, 11, 50, 928656)),
        ),
        migrations.AddField(
            model_name='author',
            name='dod',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(choices=[('A', 'AVAILABLE'), ('B', 'BORROWED'), ('M', 'MAINTENANCE')], default='A', max_length=1, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
